"""Tahoe-LAFS client operations for RedundaNet."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from redundanet.core.config import TahoeConfig
from redundanet.core.exceptions import StorageError
from redundanet.storage.introducers import write_introducers_yaml
from redundanet.utils.files import ensure_dir, write_file
from redundanet.utils.logging import get_logger
from redundanet.utils.process import is_command_available, run_command

logger = get_logger(__name__)


def _render_client_cfg(
    nickname: str,
    web_port: int,
    tub_port: int,
    tub_location: str,
    introducer_furl: str,
    shares_needed: int,
    shares_happy: int,
    shares_total: int,
    sftp_enabled: bool = False,
    sftp_port: int = 8022,
    sftp_host_pubkey: str = "private/ssh_host_rsa_key.pub",
    sftp_host_privkey: str = "private/ssh_host_rsa_key",
    sftp_accounts: str = "private/sftp_accounts",
) -> str:
    """Render tahoe.cfg for a client node (plain INI text, no templating)."""
    sftp_stanza = ""
    if sftp_enabled:
        # Tahoe's built-in SFTP frontend: exposes an account's root directory
        # capability as a normal filesystem over SFTP. Host keys + the accounts
        # file live under the node's private/ dir (persisted on the volume).
        sftp_stanza = f"""
[sftpd]
enabled = true
port = tcp:{sftp_port}
host_pubkey_file = {sftp_host_pubkey}
host_privkey_file = {sftp_host_privkey}
accounts.file = {sftp_accounts}
"""
    return f"""# Tahoe-LAFS client configuration
# Generated by RedundaNet

[node]
nickname = {nickname}
web.port = tcp:{web_port}:interface=127.0.0.1
tub.port = tcp:{tub_port}
tub.location = {tub_location}

[client]
introducer.furl = {introducer_furl}
shares.needed = {shares_needed}
shares.happy = {shares_happy}
shares.total = {shares_total}

[storage]
enabled = false

[helper]
enabled = false
{sftp_stanza}"""


@dataclass
class TahoeClientConfig:
    """Configuration for Tahoe-LAFS client."""

    nickname: str
    node_dir: Path
    introducer_furl: str
    web_port: int = 3456
    tub_port: int = 34560
    tub_location: str = "AUTO"
    shares_needed: int = 3
    shares_happy: int = 7
    shares_total: int = 10
    sftp_enabled: bool = False
    sftp_port: int = 8022
    # Additional introducers, written to private/introducers.yaml; introducer_furl
    # above stays the primary in tahoe.cfg.
    extra_introducer_furls: list[str] = field(default_factory=list)

    @classmethod
    def from_tahoe_config(
        cls,
        nickname: str,
        introducer_furl: str,
        tahoe_config: TahoeConfig,
        node_dir: Path | None = None,
        sftp_enabled: bool = False,
        sftp_port: int = 8022,
    ) -> TahoeClientConfig:
        """Create client config from TahoeConfig."""
        return cls(
            nickname=nickname,
            node_dir=node_dir or Path("/var/lib/tahoe-client"),
            introducer_furl=introducer_furl,
            shares_needed=tahoe_config.shares_needed,
            shares_happy=tahoe_config.shares_happy,
            shares_total=tahoe_config.shares_total,
            sftp_enabled=sftp_enabled,
            sftp_port=sftp_port,
        )


class TahoeClient:
    """Manages Tahoe-LAFS client node."""

    def __init__(self, config: TahoeClientConfig) -> None:
        self.config = config
        self._tahoe_cfg = config.node_dir / "tahoe.cfg"

    def ensure_tahoe_installed(self) -> bool:
        """Check if Tahoe-LAFS is installed."""
        if not is_command_available("tahoe"):
            raise StorageError("Tahoe-LAFS is not installed. Please install tahoe-lafs first.")
        return True

    def is_configured(self) -> bool:
        """Check whether this client node has already been created/configured."""
        return self._tahoe_cfg.exists()

    def update_introducers(self, furls: list[str]) -> None:
        """Point the client at these introducers.

        The first is the primary (tahoe.cfg); the rest go to
        private/introducers.yaml. Servers are learned from all of them.
        """
        if not furls:
            raise StorageError("At least one introducer FURL is required")
        self.config.introducer_furl = furls[0]
        self.config.extra_introducer_furls = list(furls[1:])
        self._write_config()
        logger.info("Updated introducers", count=len(furls))

    def update_introducer_furl(self, furl: str) -> None:
        """Update the primary introducer FURL, keeping any extra introducers."""
        self.update_introducers([furl, *self.config.extra_introducer_furls])

    def create_node(self) -> None:
        """Create a new Tahoe-LAFS client node."""
        logger.info("Creating Tahoe client node", nickname=self.config.nickname)

        self.ensure_tahoe_installed()
        ensure_dir(self.config.node_dir, mode=0o700)

        # Create the node using tahoe command
        result = run_command(
            f"tahoe create-client --basedir={self.config.node_dir} "
            f"--nickname={self.config.nickname}",
            check=False,
        )

        if not result.success and "already exists" not in result.stderr:
            raise StorageError(f"Failed to create client node: {result.stderr}")

        # Write custom configuration
        self._write_config()

        logger.info("Tahoe client node created", node_dir=str(self.config.node_dir))

    def _write_config(self) -> None:
        """Write tahoe.cfg configuration file."""
        content = _render_client_cfg(
            nickname=self.config.nickname,
            web_port=self.config.web_port,
            tub_port=self.config.tub_port,
            tub_location=self.config.tub_location,
            introducer_furl=self.config.introducer_furl,
            shares_needed=self.config.shares_needed,
            shares_happy=self.config.shares_happy,
            shares_total=self.config.shares_total,
            sftp_enabled=self.config.sftp_enabled,
            sftp_port=self.config.sftp_port,
        )

        write_file(self._tahoe_cfg, content, mode=0o600)
        logger.debug("Wrote tahoe.cfg", path=str(self._tahoe_cfg))
        # Extra introducers live in private/introducers.yaml (removed when none).
        write_introducers_yaml(self.config.node_dir / "private", self.config.extra_introducer_furls)

    # NOTE: the tahoe daemon itself is run by supervisord inside the client
    # container (`tahoe run`); file operations go through the CLI's Deployment
    # wrapper (`redundanet storage upload/download/...`), not through this class.
