"""Tahoe-LAFS client operations for RedundaNet."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from redundanet.core.config import TahoeConfig
from redundanet.core.exceptions import StorageError
from redundanet.utils.files import ensure_dir, write_file
from redundanet.utils.logging import get_logger
from redundanet.utils.process import is_command_available, run_command

logger = get_logger(__name__)


def _render_client_cfg(
    nickname: str,
    web_port: int,
    tub_port: int,
    tub_location: str,
    introducer_furl: str,
    shares_needed: int,
    shares_happy: int,
    shares_total: int,
) -> str:
    """Render tahoe.cfg for a client node (plain INI text, no templating)."""
    return f"""# Tahoe-LAFS client configuration
# Generated by RedundaNet

[node]
nickname = {nickname}
web.port = tcp:{web_port}:interface=127.0.0.1
tub.port = tcp:{tub_port}
tub.location = {tub_location}

[client]
introducer.furl = {introducer_furl}
shares.needed = {shares_needed}
shares.happy = {shares_happy}
shares.total = {shares_total}

[storage]
enabled = false

[helper]
enabled = false
"""


@dataclass
class TahoeClientConfig:
    """Configuration for Tahoe-LAFS client."""

    nickname: str
    node_dir: Path
    introducer_furl: str
    web_port: int = 3456
    tub_port: int = 34560
    tub_location: str = "AUTO"
    shares_needed: int = 3
    shares_happy: int = 7
    shares_total: int = 10

    @classmethod
    def from_tahoe_config(
        cls,
        nickname: str,
        introducer_furl: str,
        tahoe_config: TahoeConfig,
        node_dir: Path | None = None,
    ) -> TahoeClientConfig:
        """Create client config from TahoeConfig."""
        return cls(
            nickname=nickname,
            node_dir=node_dir or Path("/var/lib/tahoe-client"),
            introducer_furl=introducer_furl,
            shares_needed=tahoe_config.shares_needed,
            shares_happy=tahoe_config.shares_happy,
            shares_total=tahoe_config.shares_total,
        )


class TahoeClient:
    """Manages Tahoe-LAFS client node."""

    def __init__(self, config: TahoeClientConfig) -> None:
        self.config = config
        self._tahoe_cfg = config.node_dir / "tahoe.cfg"

    def ensure_tahoe_installed(self) -> bool:
        """Check if Tahoe-LAFS is installed."""
        if not is_command_available("tahoe"):
            raise StorageError("Tahoe-LAFS is not installed. Please install tahoe-lafs first.")
        return True

    def is_configured(self) -> bool:
        """Check whether this client node has already been created/configured."""
        return self._tahoe_cfg.exists()

    def update_introducer_furl(self, furl: str) -> None:
        """Update the introducer FURL in the configuration."""
        self.config.introducer_furl = furl
        self._write_config()
        logger.info("Updated introducer FURL")

    def create_node(self) -> None:
        """Create a new Tahoe-LAFS client node."""
        logger.info("Creating Tahoe client node", nickname=self.config.nickname)

        self.ensure_tahoe_installed()
        ensure_dir(self.config.node_dir, mode=0o700)

        # Create the node using tahoe command
        result = run_command(
            f"tahoe create-client --basedir={self.config.node_dir} "
            f"--nickname={self.config.nickname}",
            check=False,
        )

        if not result.success and "already exists" not in result.stderr:
            raise StorageError(f"Failed to create client node: {result.stderr}")

        # Write custom configuration
        self._write_config()

        logger.info("Tahoe client node created", node_dir=str(self.config.node_dir))

    def _write_config(self) -> None:
        """Write tahoe.cfg configuration file."""
        content = _render_client_cfg(
            nickname=self.config.nickname,
            web_port=self.config.web_port,
            tub_port=self.config.tub_port,
            tub_location=self.config.tub_location,
            introducer_furl=self.config.introducer_furl,
            shares_needed=self.config.shares_needed,
            shares_happy=self.config.shares_happy,
            shares_total=self.config.shares_total,
        )

        write_file(self._tahoe_cfg, content, mode=0o600)
        logger.debug("Wrote tahoe.cfg", path=str(self._tahoe_cfg))

    # NOTE: the tahoe daemon itself is run by supervisord inside the client
    # container (`tahoe run`); file operations go through the CLI's Deployment
    # wrapper (`redundanet storage upload/download/...`), not through this class.
