"""Tinc VPN management for RedundaNet."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Template

from redundanet.core.exceptions import VPNError
from redundanet.utils.files import ensure_dir, write_file
from redundanet.utils.logging import get_logger

if TYPE_CHECKING:
    from redundanet.core.config import NodeConfig

logger = get_logger(__name__)

# Tinc configuration templates
TINC_CONF_TEMPLATE = """# Tinc configuration for {{ network_name }}
# Generated by RedundaNet

Name = {{ node_name }}
Mode = router
Device = /dev/net/tun
DeviceType = tun
AddressFamily = ipv4
Port = {{ port }}

{% for connect_node in connect_to %}
ConnectTo = {{ connect_node }}
{% endfor %}

# Security settings
Compression = 9
Cipher = aes-256-cbc
Digest = sha256
"""

TINC_UP_TEMPLATE = """#!/bin/bash
# Tinc-up script for {{ network_name }}
# Generated by RedundaNet

ip link set $INTERFACE up
ip addr add {{ vpn_ip }}/32 dev $INTERFACE
ip route add {{ vpn_network }} dev $INTERFACE
"""

TINC_DOWN_TEMPLATE = """#!/bin/bash
# Tinc-down script for {{ network_name }}
# Generated by RedundaNet

ip route del {{ vpn_network }} dev $INTERFACE 2>/dev/null || true
ip addr del {{ vpn_ip }}/32 dev $INTERFACE 2>/dev/null || true
ip link set $INTERFACE down
"""

HOST_FILE_TEMPLATE = """# Host file for {{ node_name }}
# Generated by RedundaNet

Subnet = {{ vpn_ip }}/32
{% if public_ip %}Address = {{ public_ip }}{% endif %}
Port = {{ port }}

{{ public_key }}
"""


@dataclass
class TincConfig:
    """Configuration for Tinc VPN."""

    network_name: str = "redundanet"
    node_name: str = ""
    vpn_ip: str = ""
    vpn_network: str = "10.100.0.0/16"
    port: int = 655
    public_ip: str | None = None
    connect_to: list[str] = field(default_factory=list)
    config_dir: Path = field(default_factory=lambda: Path("/etc/tinc"))

    @property
    def network_dir(self) -> Path:
        """Get the network-specific configuration directory."""
        return self.config_dir / self.network_name

    @property
    def hosts_dir(self) -> Path:
        """Get the hosts directory."""
        return self.network_dir / "hosts"

    @classmethod
    def from_node_config(cls, node: NodeConfig, network_name: str = "redundanet") -> TincConfig:
        """Create TincConfig from a NodeConfig."""
        return cls(
            network_name=network_name,
            node_name=node.name,
            vpn_ip=node.vpn_ip or node.internal_ip,
            port=node.ports.tinc,
            public_ip=node.public_ip,
        )


class TincManager:
    """Manages Tinc VPN configuration and operations."""

    def __init__(self, config: TincConfig) -> None:
        self.config = config
        self._private_key_path = self.config.network_dir / "rsa_key.priv"

    def setup(self, peers: list[NodeConfig] | None = None) -> None:
        """Set up the complete Tinc configuration.

        Args:
            peers: List of peer nodes to connect to
        """
        logger.info("Setting up Tinc VPN", node=self.config.node_name)

        # Create directories
        ensure_dir(self.config.network_dir, mode=0o755)
        ensure_dir(self.config.hosts_dir, mode=0o755)

        # Determine which nodes to connect to. Only derive this from `peers` when
        # they are supplied; otherwise keep any connect_to already set on the
        # config (e.g. computed by the container entrypoint).
        if peers:
            self.config.connect_to = [
                peer.name
                for peer in peers
                if peer.is_publicly_accessible and peer.name != self.config.node_name
            ]

        # Generate configuration files
        self._write_tinc_conf()
        self._write_tinc_up()
        self._write_tinc_down()

        # The node's Tinc key is derived from its GPG identity key and must be
        # written (rsa_key.priv) before setup is called. Generating a fresh
        # standalone keypair here would silently produce a node no peer can
        # authenticate, so a missing key is an error, not a fallback.
        if not self._private_key_path.exists():
            raise VPNError(
                f"Tinc private key not found: {self._private_key_path}. "
                "Derive it from the node's GPG key first "
                "(see redundanet.vpn.gpg_tinc.gpg_secret_to_tinc_priv)."
            )
        self._ensure_local_host_file()

        # Write peer host files
        if peers:
            for peer in peers:
                if peer.name != self.config.node_name:
                    self._write_host_file(peer)

        logger.info("Tinc VPN setup complete", node=self.config.node_name)

    def _write_tinc_conf(self) -> None:
        """Write the main tinc.conf file."""
        template = Template(TINC_CONF_TEMPLATE)
        content = template.render(
            network_name=self.config.network_name,
            node_name=self.config.node_name,
            port=self.config.port,
            connect_to=self.config.connect_to,
        )

        conf_path = self.config.network_dir / "tinc.conf"
        write_file(conf_path, content, mode=0o644)
        logger.debug("Wrote tinc.conf", path=str(conf_path))

    def _write_tinc_up(self) -> None:
        """Write the tinc-up script."""
        template = Template(TINC_UP_TEMPLATE)
        content = template.render(
            network_name=self.config.network_name,
            vpn_ip=self.config.vpn_ip,
            vpn_network=self.config.vpn_network,
        )

        script_path = self.config.network_dir / "tinc-up"
        write_file(script_path, content, executable=True)
        logger.debug("Wrote tinc-up", path=str(script_path))

    def _write_tinc_down(self) -> None:
        """Write the tinc-down script."""
        template = Template(TINC_DOWN_TEMPLATE)
        content = template.render(
            network_name=self.config.network_name,
            vpn_ip=self.config.vpn_ip,
            vpn_network=self.config.vpn_network,
        )

        script_path = self.config.network_dir / "tinc-down"
        write_file(script_path, content, executable=True)
        logger.debug("Wrote tinc-down", path=str(script_path))

    def _ensure_local_host_file(self) -> None:
        """Ensure the local node's host file exists."""
        host_file = self.config.hosts_dir / self.config.node_name
        if not host_file.exists():
            header = f"# Host file for {self.config.node_name}\n"
            header += f"Subnet = {self.config.vpn_ip}/32\n"
            if self.config.public_ip:
                header += f"Address = {self.config.public_ip}\n"
            header += f"Port = {self.config.port}\n"
            write_file(host_file, header, mode=0o644)
            logger.debug("Created local host file", path=str(host_file))

    def _write_host_file(
        self,
        node: NodeConfig,
        public_key: str | None = None,
    ) -> None:
        """Write a host file for a node."""
        template = Template(HOST_FILE_TEMPLATE)
        content = template.render(
            node_name=node.name,
            vpn_ip=node.vpn_ip or node.internal_ip,
            public_ip=node.public_ip if node.is_publicly_accessible else None,
            port=node.ports.tinc,
            public_key=public_key or "",
        )

        host_path = self.config.hosts_dir / node.name
        write_file(host_path, content, mode=0o644)
        logger.debug("Wrote host file", node=node.name, path=str(host_path))

    # NOTE: tincd itself is exec'd by the container entrypoint
    # (docker/entrypoints/tinc.py); the CLI drives it through docker compose.
    # This class only generates configuration.
