network:
  name: redundanet
  version: 2.0.0
  domain: redundanet.local
  vpn_network: 10.100.0.0/16
  tahoe:
    shares_needed: 1
    shares_happy: 2
    shares_total: 2
    reserved_space: 1G
introducer_furl: pb://iufhp7il422sofdh5hkpc36l3famhg7x@tcp:10.100.0.1:3458/fjogqdpcjjbuug7gs6tp7aylmi6lq627
nodes:
- name: hub-fly
  internal_ip: 10.100.0.1
  vpn_ip: 10.100.0.1
  public_ip: 149.248.198.15
  gpg_key_id: F9151151771C34F4E23BB64BF16283B50D5AD27F
  region: europe
  status: active
  roles:
  - tinc_vpn
  - tahoe_introducer
  ports:
    tinc: 655
    tahoe_storage: 3457
    tahoe_client: 3456
    tahoe_introducer: 3458
  is_publicly_accessible: true
- name: node-2680cd08
  internal_ip: 10.100.0.10
  vpn_ip: 10.100.0.10
  gpg_key_id: DB36ED4F7D2D2EC7726387466F11FA662680CD08
  region: europe
  status: active
  roles:
  - tinc_vpn
  - tahoe_storage
  ports:
    tinc: 655
    tahoe_storage: 3457
    tahoe_client: 3456
    tahoe_introducer: 3458
  storage_contribution: 900GB
  is_publicly_accessible: false
- name: node-bae1b9cd
  internal_ip: 10.100.0.11
  vpn_ip: 10.100.0.11
  gpg_key_id: 898D9F16D48446877DF21F2C18F8CB7CBAE1B9CD
  region: europe
  status: active
  roles:
  - tinc_vpn
  - tahoe_storage
  ports:
    tinc: 655
    tahoe_storage: 3457
    tahoe_client: 3456
    tahoe_introducer: 3458
  storage_contribution: 900GB
  is_publicly_accessible: false
- name: node-303c084b
  internal_ip: 10.100.0.12
  vpn_ip: 10.100.0.12
  gpg_key_id: 1331C835A2B446B61A34959CD5294DA9303C084B
  region: europe
  status: active
  roles:
  - tinc_vpn
  - tahoe_storage
  ports:
    tinc: 655
    tahoe_storage: 3457
    tahoe_client: 3456
    tahoe_introducer: 3458
  storage_contribution: 1TB
  is_publicly_accessible: false
- name: node-e418302c
  internal_ip: 10.100.0.13
  vpn_ip: 10.100.0.13
  gpg_key_id: D41D09F293F89FA18948933682385B9CE418302C
  region: europe
  status: pending
  roles:
  - tinc_vpn
  - tahoe_storage
  ports:
    tinc: 655
    tahoe_storage: 3457
    tahoe_client: 3456
    tahoe_introducer: 3458
  storage_contribution: 1TB
  is_publicly_accessible: false
