#!/usr/bin/env python3
"""Tahoe-LAFS Introducer container entrypoint for RedundaNet."""

import os
import subprocess
import sys
import time
from pathlib import Path

from redundanet.utils.logging import setup_logging, get_logger


def wait_for_vpn(timeout: int = 300) -> bool:
    """Wait for VPN interface to be available."""
    logger = get_logger()
    start_time = time.time()

    while time.time() - start_time < timeout:
        try:
            result = subprocess.run(
                ["ip", "link", "show", "tinc0"],
                capture_output=True,
                text=True,
            )
            if result.returncode == 0:
                logger.info("VPN interface is available")
                return True
        except Exception:
            pass

        logger.debug("Waiting for VPN interface...")
        time.sleep(5)

    logger.error("Timeout waiting for VPN interface")
    return False


def create_introducer(node_dir: Path, nickname: str, vpn_ip: str, port: int) -> bool:
    """Create and configure the Tahoe introducer node."""
    logger = get_logger()

    tahoe_cfg = node_dir / "tahoe.cfg"

    # If already configured, skip creation
    if tahoe_cfg.exists():
        logger.info("Introducer already configured")
        return True

    logger.info("Creating new Tahoe introducer", nickname=nickname)

    # Create the introducer node structure
    result = subprocess.run(
        ["tahoe", "create-introducer", "--listen=none", str(node_dir)],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0 and "already exists" not in result.stderr:
        logger.error("Failed to create introducer", error=result.stderr)
        return False

    # Write custom configuration (introducer only needs [node] section)
    # Use different ports for web (port+1000) and tub (port)
    web_port = port + 1000
    config_content = f"""# Tahoe-LAFS introducer configuration
# Generated by RedundaNet

[node]
nickname = {nickname}
web.port = tcp:{web_port}:interface=0.0.0.0
tub.port = tcp:{port}
tub.location = tcp:{vpn_ip}:{port}
"""

    tahoe_cfg.write_text(config_content)
    logger.info("Wrote tahoe.cfg configuration")

    return True


def main():
    """Main entrypoint for Tahoe Introducer container.

    This script sets up the introducer configuration, then exits.
    Supervisord will then start the actual tahoe process.
    """
    setup_logging(level=os.environ.get("REDUNDANET_LOG_LEVEL", "INFO"))
    logger = get_logger()

    logger.info("Setting up RedundaNet Tahoe Introducer")

    # Get configuration from environment
    node_name = os.environ.get("REDUNDANET_NODE_NAME")
    vpn_ip = os.environ.get("REDUNDANET_INTERNAL_VPN_IP")
    test_mode = os.environ.get("REDUNDANET_TEST_MODE", "false").lower() == "true"

    if not node_name:
        logger.error("REDUNDANET_NODE_NAME environment variable is required")
        sys.exit(1)

    if not vpn_ip:
        logger.error("REDUNDANET_INTERNAL_VPN_IP environment variable is required")
        sys.exit(1)

    # Paths
    introducer_dir = Path("/var/lib/tahoe-introducer")

    # Wait for VPN to be available (skip in test mode)
    if not test_mode:
        if not wait_for_vpn():
            logger.error("VPN not available, cannot start introducer")
            sys.exit(1)
    else:
        logger.info("Test mode: skipping VPN wait")

    # Create and configure introducer
    if not create_introducer(
        node_dir=introducer_dir,
        nickname=f"{node_name}-introducer",
        vpn_ip=vpn_ip,
        port=3458,
    ):
        logger.error("Failed to create introducer")
        sys.exit(1)

    logger.info("Tahoe introducer setup complete")


if __name__ == "__main__":
    main()
